# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_update_pb2 as model__update__pb2


class FederatedLearningServiceStub(object):
    """Extended service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitUpdate = channel.unary_unary(
                '/federated.FederatedLearningService/SubmitUpdate',
                request_serializer=model__update__pb2.ModelUpdate.SerializeToString,
                response_deserializer=model__update__pb2.Acknowledgement.FromString,
                )
        self.GetAggregatedModel = channel.unary_unary(
                '/federated.FederatedLearningService/GetAggregatedModel',
                request_serializer=model__update__pb2.ClientRequest.SerializeToString,
                response_deserializer=model__update__pb2.AggregatedModel.FromString,
                )
        self.ConnectClient = channel.unary_unary(
                '/federated.FederatedLearningService/ConnectClient',
                request_serializer=model__update__pb2.ClientConnection.SerializeToString,
                response_deserializer=model__update__pb2.ModelVersionInfo.FromString,
                )
        self.SubscribeToUpdates = channel.unary_stream(
                '/federated.FederatedLearningService/SubscribeToUpdates',
                request_serializer=model__update__pb2.ClientRequest.SerializeToString,
                response_deserializer=model__update__pb2.UpdateNotification.FromString,
                )


class FederatedLearningServiceServicer(object):
    """Extended service definition
    """

    def SubmitUpdate(self, request, context):
        """Existing RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregatedModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectClient(self, request, context):
        """New RPCs for hybrid approach
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUpdate,
                    request_deserializer=model__update__pb2.ModelUpdate.FromString,
                    response_serializer=model__update__pb2.Acknowledgement.SerializeToString,
            ),
            'GetAggregatedModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregatedModel,
                    request_deserializer=model__update__pb2.ClientRequest.FromString,
                    response_serializer=model__update__pb2.AggregatedModel.SerializeToString,
            ),
            'ConnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectClient,
                    request_deserializer=model__update__pb2.ClientConnection.FromString,
                    response_serializer=model__update__pb2.ModelVersionInfo.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=model__update__pb2.ClientRequest.FromString,
                    response_serializer=model__update__pb2.UpdateNotification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.FederatedLearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederatedLearningService(object):
    """Extended service definition
    """

    @staticmethod
    def SubmitUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.FederatedLearningService/SubmitUpdate',
            model__update__pb2.ModelUpdate.SerializeToString,
            model__update__pb2.Acknowledgement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAggregatedModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.FederatedLearningService/GetAggregatedModel',
            model__update__pb2.ClientRequest.SerializeToString,
            model__update__pb2.AggregatedModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.FederatedLearningService/ConnectClient',
            model__update__pb2.ClientConnection.SerializeToString,
            model__update__pb2.ModelVersionInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/federated.FederatedLearningService/SubscribeToUpdates',
            model__update__pb2.ClientRequest.SerializeToString,
            model__update__pb2.UpdateNotification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
